-- DROP DATABASE optica_cul_ampolla;
-- CREATE SCHEMA IF NOT EXISTS optica_cul_ampolla;
USE optica_cul_ampolla;
-- -- *--------------------------------------------------------------------------------------------
-- -- *QUERIES per crear les taules
-- -- *--------------------------------------------------------------------------------------------
-- DROP TABLE proveïdors;
-- CREATE TABLE IF NOT EXISTS proveïdors (
--     id SERIAL PRIMARY KEY,
--     nom_proveïdor VARCHAR(100) NOT NULL,
--     adreça VARCHAR(200) NOT NULL,
--     telefon VARCHAR(100) NOT NULL,
--     fax VARCHAR(100),
--     nif VARCHAR(100) NOT NULL
-- );
-- -- *--------------------------------------------------------------------------------------------
-- DROP TABLE ulleres;
-- CREATE TABLE ulleres (
--     id SERIAL PRIMARY KEY,
--     nom_proveïdor VARCHAR(100) REFERENCES proveïdors(nom_proveïdor) ON DELETE CASCADE,
--     marca VARCHAR(100) NOT NULL,
--     graduacio VARCHAR(50) NOT NULL,
--     tipus_muntura ENUM('flotant', 'pasta', 'metàl·lica') NOT NULL,
--     color_muntura VARCHAR(50) NOT NULL,
--     color_vidres VARCHAR(50) NOT NULL,
--     preu FLOAT(5,2) NOT NULL
-- );
-- -- *--------------------------------------------------------------------------------------------
-- DROP TABLE clients;
-- CREATE TABLE clients (
--     id SERIAL PRIMARY KEY,
--     nom VARCHAR(100) NOT NULL,
--     adreça VARCHAR(200) NOT NULL,
--     telefon VARCHAR(100) NOT NULL,
--     email VARCHAR(100) NOT NULL,
--     nif VARCHAR(100) NOT NULL,
--     client_recomanador VARCHAR(100),
--     data_registre TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );
-- -- *--------------------------------------------------------------------------------------------
-- CREATE TABLE vendes (
--     id SERIAL PRIMARY KEY,
--     empleat_venedor VARCHAR(100),
--     marca_venuda VARCHAR(100) REFERENCES ulleres(marca) ON DELETE CASCADE,
--     client VARCHAR(100) REFERENCES clients(nom),
--     data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- )
-- *--------------------------------------------------------------------------------------------
-- *QUERIES per poblar les taules
-- *--------------------------------------------------------------------------------------------
-- INSERT INTO vendes (empleat_venedor, marca_venuda, client)
-- VALUES
--     ("Mario", "TomFord", "Mercuri"),
--     ("Mario", "Vogue", "Venus"),
--     ("Mario", "PRADA", "Mart"),
--     ("Mario", "PRADA", "Mart"),
--     ("Luigi", "Emporio", "Venus"),
--     ("Luigi", "Emporio", "Mercuri");
-- INSERT INTO proveïdors (nom_proveïdor, adreça, telefon, fax, nif)
-- VALUES 
--     ("Alfa", "Carrer 3 num 5 08085 TER SPAIN", "932093129", "934054844", "47872216W"),
--     ("Bravo", "Carrer 7 num 1 08090 BAD SPAIN", "932043129", "935054844", "47872211X"),
--     ("Charly", "Carrer 1 num 3 08081 BCN SPAIN", "932092129", "932054844", "47872216Q"),
--     ("Delta", "Carrer 2 num 4 08082 SAB SPAIN", "932092120", "932054845", "47872216Y");
-- -- *--------------------------------------------------------------------------------------------
-- INSERT INTO clients (nom, adreça, telefon, email, nif, client_recomanador)
-- VALUES 
--     ("Mercuri", "Tallers 10, num 5 08012 BCN SPAIN", "913185577", "mercuri@mercuri.com", "47872216M", null),
--     ("Venus", "Tigre 8, num 9 08019 BCN SPAIN", "913185577", "venus@venus.com", "47872216V", "Mercuri"),
--     ("Mart", "Joaquim Costa 20, num 7 08013 BCN SPAIN", "913185577", "mart@mart.com", "47872216M", null),
--     ("Saturn", "Elisabeths 30, num 2 08014 BCN SPAIN", "913185577", "saturn@saturn.com", "47872216S", "Mart");
-- -- *--------------------------------------------------------------------------------------------
-- INSERT INTO ulleres (nom_proveïdor, marca, graduacio, tipus_muntura, color_muntura, color_vidres, preu)
-- VALUES 
    -- ("Alfa", "TomFord", "2.5,3.5", "metàl·lica", "blau", "blanc", 180.99),
    -- ("Alfa", "TomFord", "2.5,3.5", "pasta", "groc", "blanc", 90.99),
    -- ("Alfa", "TomFord", "2.5,3.5", "flotant", "lila", "blanc", 70.99),
    -- ("Bravo", "PRADA", "-2,-2", "metàl·lica", "vermell", "daurat", 150.99),
    -- ("Bravo", "PRADA", "-2,-2", "pasta", "negre", "daurat", 125.99),
    -- ("Charly", "Vogue", "-4,-3.5", "pasta", "blau", "platejat", 200.99),
    -- ("Charly", "Vogue", "-4,-3.5", "flotant", "coral", "platejat", 190.99),
    -- ("Delta", "Emporio", "-3.5,-3.5", "metàl·lica", "sepia", "negre", 50.99),
    -- ("Delta", "Emporio", "-3.5,-3.5", "flotant", "taronja", "negre", 60.99);
-- *--------------------------------------------------------------------------------------------
-- *QUERIES de comprovació
-- *--------------------------------------------------------------------------------------------
-- Llista el total de compres d’un client/a.
SELECT * FROM vendes WHERE client="Venus";

-- Llista les diferents ulleres que ha venut un empleat durant un any.



-- Llista els diferents proveïdors que han subministrat ulleres venudes amb èxit per l'òptica.

